#!/usr/bin/env python

"""
Installation makefile generator
"""

sources = [ 'src/xmpp.py' ]
extras = ['LICENCE', 'README']
bins = ['j2m_gw']

import sys
import os.path
from os.path import basename

m = open('Makefile.in', 'wt')
m.write("# Makefile is automatically generated by %s script\n" % sys.argv[0])
m.write("PREFIX = @prefix@\n")
m.write("NAME = @PACKAGE_NAME@\n")
m.write("INSTALL = @INSTALL@\n")
m.write("SRCDIR = @srcdir@\n")
m.write("SOURCES_DIR = $(PREFIX)/share/$(NAME)/src\n")
m.write("EXTRAS_DIR = $(PREFIX)/share/$(NAME)\n")
m.write("BIN_DIR = $(PREFIX)/bin\n")
m.write("all:\n")
m.write("\t@echo 'Nothing to do for all'\n\n")
m.write("install: create_install_dirs install_src install_extras install_bins\n\n")
m.write("install_src: %s\n\n" % " ".join(["$(SOURCES_DIR)/%s" % basename(n) for n in sources]))
m.write("install_extras: %s\n\n" % " ".join(["$(EXTRAS_DIR)/%s" % basename(n) for n in extras]))
m.write("install_bins: %s\n\n" % " ".join(["$(BIN_DIR)/%s" % basename(n) for n in bins]))

for f in sources:
	m.write("$(SOURCES_DIR)/%s: $(SRCDIR)/%s\n" % (basename(f), f))
	m.write("\t$(INSTALL) -m 644 $(SRCDIR)/%s $(SOURCES_DIR)/%s\n\n" % (f, basename(f)))

for f in extras:
	m.write("$(EXTRAS_DIR)/%s: $(SRCDIR)/%s\n" % (basename(f), f))
	m.write("\t$(INSTALL) -m 644 $(SRCDIR)/%s $(EXTRAS_DIR)/%s\n\n" % (f, basename(f)))

for f in bins:
	m.write("$(BIN_DIR)/%s: $(SRCDIR)/%s\n" % (basename(f), f))
	m.write("\t$(INSTALL) -m 755 $(SRCDIR)/%s $(BIN_DIR)/%s\n\n" % (f, basename(f)))

m.write("uninstall:\n")
for f in sources:
	m.write("\t@rm -f $(SOURCES_DIR)/%s\n" % basename(f))
for f in extras:
	m.write("\t@rm -f $(EXTRAS_DIR)/%s\n" % basename(f))
for f in bins:
	m.write("\t@rm -f $(BIN_DIR)/%s\n" % basename(f))

m.write("\n\n")
m.write("create_install_dirs:\n")
m.write("\tmkdir -p $(SOURCES_DIR)\n")
m.write("\tmkdir -p $(EXTRAS_DIR)\n")
m.write("\tmkdir -p $(BIN_DIR)\n")

